# Generated by Django 4.2.16 on 2024-09-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=254)),
                ("author", models.CharField(max_length=254)),
                ("copies", models.PositiveIntegerField(default=0)),
                ("available", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField()),
                ("created_by", models.CharField(max_length=254)),
                ("updated_by", models.CharField(max_length=254)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["title"], name="books_title_idx"),
                    models.Index(fields=["author"], name="books_author_idx"),
                    models.Index(fields=["copies"], name="books_copies_idx"),
                    models.Index(fields=["available"], name="books_available_idx"),
                ],
            },
        ),
    ]
