# Generated by Django 4.2.16 on 2024-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="books",
            name="updated_by",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
